### ISSUE TITLE
Testing w/ RSPduo on 22.04 

### ISSUE THREAD

**Issue by alphafox02** [30hours/blah2#1]
Quickly tested on a 22.04 host machine following the steps provided and using the RSPduo. I see the following happening, and I will say sdrplay api sometimes gives me issues where I'll have to kill/restart the systemctl sdrplay service. That happens with various applications thought, but back to blah2 specifically.

`blah2      | Setting up device RspDuo
blah2      | Info - get_device - MaxDevs=1023 NumDevs=1
blah2      | Info - get_device - Dev0: SerNo=1905090B32 hwVer=3 tuner=0x03 rspDuoMode=0x07
blah2      | Info - get_device - chosenDevice=0
blah2      | Info - get_device - Dev0: selected rspDuoMode=0x02 tuner=0x03 rspDuoSampleFreq=6000000.0
blah2      | 
blah2      | fc (Hz)                       : 204640000
blah2      | file                          : 
blah2      | wait_time_nr (s)              : 2
blah2      | chunk_time_nr (s)             : 0
blah2      | agc_bandwidth_nr (Hz)         : 50
blah2      | agc_set_point_nr (dBfs)       : -60
blah2      | gain_reduction_nr (dB)        : 40
blah2      | lna_state_nr                  : 4
blah2      | N_DECIMATION                  : 1
blah2      | rf_notch_fg                   : false
blah2      | dab_notch_fg                  : false
blah2      | usb_bulk_fg                   : false
blah2      | stats_fg                      : true
blah2      | small_verbose_fg              : false
blah2      | more_verbose_fg               : false
blah2      | 
blah2      | Info - event_callback - GainChange tuner=sdrplay_api_Tuner_A gRdB=40 lnaGRdB=20 systemGain=53.09
blah2      | Info - event_callback - GainChange tuner=sdrplay_api_Tuner_B gRdB=40 lnaGRdB=20 systemGain=52.80
blah2      | /blah2/lib/rapidyaml-0.5.0/ryml-0.5.0.hpp:19396:check failed: has_val(node)
blah2      | Aborted (core dumped)
blah2-api  | node:events:491
blah2-api  |       throw er; // Unhandled 'error' event

`

and 

`blah2-api  | Running on http://0.0.0.0:3000                                                                              
blah2      | Setting up device RspDuo
blah2      | Info - get_device - MaxDevs=1023 NumDevs=0
blah2      | Error - get_device - no devices found
blah2-api  | node:events:491
blah2-api  |       throw er; // Unhandled 'error' event
blah2-api  |       ^
blah2-api  | 
blah2-api  | Error: read ECONNRESET
blah2-api  |     at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
blah2-api  | Emitted 'error' event on Socket instance at:
blah2-api  |     at emitErrorNT (node:internal/streams/destroy:157:8)
blah2-api  |     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
blah2-api  |     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
blah2-api  |   errno: -104,
blah2-api  |   code: 'ECONNRESET',
blah2-api  |   syscall: 'read'
blah2-api  | }
blah2-api exited with code 1
blah2 exited with code 1    
`

SoapySDRUtil --find does initially find the RSPduo and it's usable in other applications.

**Comment by 30hours** [comment]
You're right - had the same issue when using config/config.yml. In development I've been using config/radar4.yml - so they must've deviated which is where the parsing error is coming from. As a temporary solution, in the docker-compose.yml try changing;

`    command: >
      sh -c "/blah2/bin/blah2 -c config/config.yml"`

to;

`    command: >
      sh -c "/blah2/bin/blah2 -c config/radar4.yml"`

I'll update the standard config file soon - let me know how it goes.

**Comment by alphafox02** [comment]
That fixed it! Running great now, but I need to get out by this tower to use as a reference signal. I've never used passive radar, not even with the kerberosdr/krakensdr. Suppose I better get some directional antennas.

**Comment by 30hours** [comment]
Great! Don’t stress about getting too strong of a reference signal. In the blah2 logs you’ll see a signal level for each channel, and I’m barely hitting 20% of full scale. Please do email through some delay Doppler maps once you have it running (email on the contact page at 30hours.dev).
