### ISSUE TITLE
KerberosSDR

### ISSUE THREAD

**Issue by ea4gja** [30hours/blah2#23]
I can read that you plan to add support for 5-channel KrakenSDR, to use all 5 channels. Please consider to make this feature backwards-compatible with KerberosSDR, the 4-channel version of KrakenSDR.

**Comment by 30hours** [comment]
Ack and will do. The Kerberos doesn't have a in-built noise source as with the Kraken SDR. Instructions for calibration on the Kerberos SDR will be something along the lines of plug in a noise source to all 4 channels during calibration. In terms of radar processing there shouldn't be any issues.
