### ISSUE TITLE
docker-compose.yml network_mode

### ISSUE THREAD

**Issue by sdn-ninja** [30hours/blah2#9]
There is a problem with having network_mode : host in line 22, and line 45

This config isn't compatible with the most recent version of docker-compose on Fedora 39 (latest).

I had to comment out that line to run the image.

The problem is also described here: https://forums.docker.com/t/docker-errors-invalidargument-host-network-mode-is-incompatible-with-port-bindings/103492/14

tl;dr
Running network mode as host and port binding isn't a valid docker option, it used to be ignored, but now enforced. I suspect you are running this on Ubuntu which is still not packaging latest docker-compose

**Comment by 30hours** [comment]
You're correct, there must be a difference between our docker-compose and docker compose. Anyway this is a frustrating problem to fix. Ideally the blah2 and blah2_api service would run in their own network. I tried this and then API calls from blah2 should be `http://blah2_api:8080`. This was not working and gave connection refused errors. Seems to be some issue with the asio library and Docker. Instead my temporary solution (may be a while) is to run blah2 and blah2_api in host mode. This means I also had to change the blah2_api Dockerfile to be port 3000. Please feel free to try and fix this but I probably won't come back until some more key functionality is added.

**Comment by 30hours** [comment]
Commit pushed as per above! Thanks again!
